dijes = [
    {"titulo": "Dije Serpentina Rolado Con Pino", "color": "Serpentina"},
    {"titulo": "Dije Onix Negro Con Pino", "color": None},
    {"titulo": "Dijes En Cuarzos Amatista", "color": "Amatista"},
    {"titulo": "Dijes En Cuarzos Rosa", "color": "Rosa"},
    {"titulo": "Dijes En Cuarzos Cristal", "color": "Cristal"},
    {"titulo": "Dijes En Cuarzos Citrino", "color": "Citrino"},
    {"titulo": "Dijes En Cuarzos Cuarzo Azul", "color": "Cuarzo Azul"},
    {"titulo": "Dijes En Cuarzos Cuarzo Verde", "color": "Cuarzo Verde"},
    {"titulo": "Dijes En Cuarzos Cuarzo Ahumado", "color": "Ahumado"},
    {"titulo": "Dijes En Cuarzos Cuarzo Rojo", "color": "Cuarzo Rojo"},
    {"titulo": "Dije Coral Chico (Teñido)", "color": None},
    {"titulo": "Dijes Agatas Agata Verde", "color": "Agata Verde"},
    {"titulo": "Dijes Agatas Cornalina", "color": "Cornalina"},
    {"titulo": "Dijes Agatas Agata Azul", "color": "Agata Azul"},
    {"titulo": "Dijes Agatas Agata Fucsia", "color": "Agata Fucsia"},
    {"titulo": "Dije Punta Cristal Chica Con Pinodije Hematite", "color": "Hematite"},
    {"titulo": "Dije Jaspe Rojo", "color": "Jaspe Rojo"},
    {"titulo": "Dije Ojo De Gato", "color": "Ojo De Gato"},
    {"titulo": "Dije Turmalina Chic", "color": None},
    {"titulo": "Dije Ojo De Tigre Cabujon Con Engarce De Alpaca X Gramo", "color": "Ojo De Tigre"},
    {"titulo": "Dije Lapislázuli Cabujon Con Engarce De Alpaca X Gramo", "color": None},
    {"titulo": "Dije Amazonita Cabujon Con Engarce De Alpaca X Gramo", "color": "Amazonita"},
    {"titulo": "Dije Agata Musgosa Cabujon Con Engarce Alpaca X Gramos", "color": None},
    {"titulo": "Dije Cuarzo Rosa Cabujon Con Engarce De Alpaca X Gramo", "color": "Cuarzo Rosa"},
    {"titulo": "Dije Labradorita Cabujon Engarce Alpaca X Gramo", "color": None},
    {"titulo": "Dije Amatista Cabujon Con Engarce Alpaca X Gramo", "color": "Amatista"},
    {"titulo": "Dije Obsidiana Negra", "color": "Obsidiana Negra"},
    {"titulo": "Dije Obsidiana Nevada", "color": "Obsidiana Nevada"},
    {"titulo": "Dije Ojo De Tigre", "color": "Ojo De Tigre"},
    {"titulo": "Dije Sodalita Con Pino", "color": "Sodalita"},
    {"titulo": "Dije Rolado Dorado", "color": None},
    {"titulo": "Dije Rolado Con Pino Dorado Comunes", "color": None},
    {"titulo": "Dije Palito Escalla 7 Chacras", "color": None},
    {"titulo": "Dije Selenita Mediano Con Pino", "color": None},
    {"titulo": "Dije Amatista Kenya En Bruto Con Pino", "color": "Amatista"},
    {"titulo": "Dije Heliotropo Jaspe Sanguineo Con Pino", "color": None},
    {"titulo": "Dije Rolado Chico Con Alambre Acero", "color": None},
    {"titulo": "Dije Dumorterita Con Pino En Niquel", "color": None},
    {"titulo": "Dije Amazonita Brasil", "color": None},
    {"titulo": "Dije Unakita", "color": None},
    {"titulo": "Dije Cuarzo Verde Grande Con Pino", "color": "Cuarzo Verde"},
    {"titulo": "Dije Jaspe Dalmata Con Pino", "color": "Jaspe Dalmata"},
    {"titulo": "Dije Ojo De Buey Chico", "color": "Ojo De Buey"},
    {"titulo": "Dije Rodonita", "color": None},
    {"titulo": "Dije Punta Cristal Mediana Oferta", "color": "Cristal"},
    {"titulo": "Dije Pirita Mediano", "color": None},
    {"titulo": "Dije Turquenita (Howlita Teñida)", "color": "Howlita"},
    {"titulo": "Dije Rosa Del Desierto Con Pino", "color": None},
    {"titulo": "Dije Pico Amatista/Turmalina/Cristal/Ahumado Con Alambre Alpaca/Acero", "color": ["Amatista", "Turmalina", "Cristal", "Ahumado"]},
    {"titulo": "Dije Ojo De Tigre Grande Con Pino", "color": "Ojo De Tigre"},
    {"titulo": "Dije Pico Amatista Chico Con Pino", "color": "Amatista"},
    {"titulo": "Dije Pirita Grande Con Pino", "color": None},
    {"titulo": "Dije Aguamarina", "color": None},
    {"titulo": "Dije Lluvia De Estrellas (Vidrio)", "color": "Lluvia De Estrellas"},
    {"titulo": "Dije Lapislazuli", "color": "Lapislazuli"},
    {"titulo": "Dije Jade Olivo", "color": None},
    {"titulo": "Dije Cuarzo Rosa Bruto Con Pino", "color": "Cuarzo Rosa"},
    {"titulo": "Dije Opalina (Vidrio) Con Pino", "color": None},
    {"titulo": "Dije Topacio Imperial Chico Oferta", "color": None},
    {"titulo": "Dije Hojitas En Onix Azul", "color": None},
    {"titulo": "Iangulito Chico Con Pino", "color": None},
    {"titulo": "Dije Pendulo Honguito", "color": None},
    {"titulo": "Dije Elefante Chico Con Pino", "color": None},
    {"titulo": "Dije Fluorita Arcoiris", "color": None},
    {"titulo": "Dije Piramide Prisma (Doble)", "color": None},
    {"titulo": "Dije Alita Mini", "color": None},
    {"titulo": "Dije Corazon Mini Con Pino", "color": None},
    {"titulo": "Dije Estrella Mini", "color": None},
    {"titulo": "Dije Gota Mini Con Pino", "color": None},
    {"titulo": "Dije Hexagono Mini", "color": None},
    {"titulo": "Dije Ovalito Chico Con Pino", "color": None},
    {"titulo": "Dije Pendulo Mini", "color": None},
    {"titulo": "Dije Triangulo Mini Con Pino", "color": None},
    {"titulo": "Dije Alitas De Angel En Onix Azul", "color": None},
    {"titulo": "Dije Rayo Con Capuchon Baño De Plata", "color": None},
    {"titulo": "Dije Corazon Mini Virola", "color": None},
    {"titulo": "Dije Gota Mini Virola", "color": None},
    {"titulo": "Dije Piramide Mini Con Virola", "color": None},
    {"titulo": "Dije Punta De Flecha Mini Con Pino", "color": None},
    {"titulo": "Dije Bolita Mini", "color": None},
    {"titulo": "Dije Labradorita", "color": None},
    {"titulo": "Dije Oval Mini Con Virola", "color": None},
    {"titulo": "Dije Alita Mediana", "color": None},
    {"titulo": "Dije Circulo Intermedio 20 Mm Con Virola", "color": None},
    {"titulo": "Dije Punta Ahumado Chico Con Baño De Plata", "color": "Ahumado"},
    {"titulo": "Dije Rolado Con Baño Dorado", "color": None},
    {"titulo": "Dije Cruz Del Equilibrio Chica Capuchon", "color": None},
    {"titulo": "Dijes En Bruto Con Baño Dorado", "color": None},
    {"titulo": "Dije Corazón Onix Cielo 20 Mm", "color": "Onix Cielo"},
    {"titulo": "Dije Tortuga Onix Cielo", "color": "Onix Cielo"},
    {"titulo": "Dije Rolado Chico Con Baño De Plata", "color": None},
    {"titulo": "Dije Pico Amatista Chico Electro", "color": "Amatista"},
    {"titulo": "Dije Pico Citrino Chico Con Electro", "color": "Citrino"},
    {"titulo": "Dije Pico Cristal Chico Electro", "color": "Cristal"},
    {"titulo": "Dije Selenita Chica Con Baño De Plata", "color": None},
    {"titulo": "Dije Turmalina Chica Con Electro", "color": "Turmalina"},
    {"titulo": "Dije Biterminal Chico", "color": None},
    {"titulo": "Dije Cianita Negra Chica (Escoba De Bruja) Con Baño De Plata", "color": "Cianita Negra"},
    {"titulo": "Dije Bolita Mediano", "color": None},
    {"titulo": "Dije Bruto Con Electro (Baño De Plata)", "color": None},
    {"titulo": "Dije Shungit Petrovsky 80% Carbon", "color": None},
    {"titulo": "Dije Crisocola Namibia", "color": None},
    {"titulo": "Dije Mariposa Onix", "color": None},
    {"titulo": "Dije Pendulo Intermedio", "color": None},
    {"titulo": "Dije Estrella Merkaba 3D", "color": None},
    {"titulo": "Dije Colmillo", "color": None},
    {"titulo": "Dije Circulo 25 Mm Bombe Con Virola", "color": None},
    {"titulo": "Dije Figa Mediana Con Baño De Plata", "color": None},
    {"titulo": "Dije Triangulo Curvo Con Virola", "color": None},
    {"titulo": "Dije Chacana 3 X 3 Cm", "color": None},
    {"titulo": "Dije Corazon Intermedio Con Pino", "color": None},
    {"titulo": "Dije Rolado Mediano Con Electro (Baño De Plata)", "color": None},
    {"titulo": "Dije Ficha 17 Mm Con Electro (Baño De Plata)", "color": None},
    {"titulo": "Dije Circulo Con Virola 30 Mm", "color": None},
    {"titulo": "Dije Opalina Mediana Con Electro (Baño De Plata)", "color": None},
    {"titulo": "Dije Cianita Azul Mediana Electro (Baño De Plata)", "color": "Cianita Azul"},
    {"titulo": "Dije Pico Amatista Mediano Electro", "color": "Amatista"},
    {"titulo": "Dije Pico Citrino Mediano Electro", "color": "Citrino"},
    {"titulo": "Dije Punta Cristal Mediana Electro", "color": "Cristal"},
    {"titulo": "Dije Selenita Mediana Electro", "color": None},
    {"titulo": "Dije Turmalina Mediana Con Electro", "color": "Turmalina"},
    {"titulo": "Dije Corazon Intermedio Con Virola", "color": None},
    {"titulo": "Dije Turmalina Negra Con Engarce Alpaca", "color": "Turmalina Negra"},
    {"titulo": "Dije Tubito Chico", "color": None},
    {"titulo": "Dije Péndulo Orgon", "color": None},
    {"titulo": "Dije Gota Mediana Con Pino", "color": None},
    {"titulo": "Dije Gota Mediana Con Virola", "color": None},
    {"titulo": "Dije Malaquita Natural Con Pino", "color": "Malaquita"},
    {"titulo": "Dijes Cuarzo Vidente", "color": None},
    {"titulo": "Dije Aguamarina Bruto Con Baño De Plata", "color": "Aguamarina"},
    {"titulo": "Dije Puntacitrino Grande Con Electro", "color": "Citrino"},
    {"titulo": "Dije Pico Amatista Grande Electro", "color": "Amatista"},
    {"titulo": "Dije Pico Cristal Grande Electro", "color": "Cristal"},
    {"titulo": "Dije Turmalina Grande Electro", "color": "Turmalina"},
    {"titulo": "Dije Oval Grande Con Virola", "color": None},
    {"titulo": "Dije Ficha 30 Mm Con Electro", "color": None},
    {"titulo": "Dije Punta De Flecha Con Electro", "color": None},
    {"titulo": "Dije Colmillo Con Baño De Plata", "color": None},
    {"titulo": "Dije Ala Cabujon", "color": None},
    {"titulo": "Dije Mano De Fatima Con Cabujon", "color": None},
    {"titulo": "Dije Chapa Geoda Ágata Con Electro", "color": None},
    {"titulo": "Dije Ficha 35 Mm Con Electro", "color": None},
    {"titulo": "Dije Chapas Agata Chicas Con Baño", "color": None},
    {"titulo": "Dije Palito Con Diseño", "color": None},
    {"titulo": "Dije Candado Simple", "color": None},
    {"titulo": "Dije Haditas", "color": None},
    {"titulo": "Dije Buho Con Baño De Plata", "color": None},
    {"titulo": "Dije Angel Gota", "color": None},
    {"titulo": "Dije Selenita Con Aplique", "color": "Selenita"},
    {"titulo": "Dije Chapas Agata Grande Con Electro", "color": None},
    {"titulo": "Pendulo Con Cadena Comun", "color": None},
    {"titulo": "Dije Ficha 45 Mm Con Electro", "color": None},
    {"titulo": "Dije Delfin Con Baño De Plata", "color": None},
    {"titulo": "Dije Corazón Con Diseño", "color": None},
    {"titulo": "Dije Ojo De Orus Cabujon", "color": None},
    {"titulo": "Dije Ficha 50 Mm Con Electro", "color": None},
    {"titulo": "Dije Corazón Doble Con Baño De Plata", "color": None},
    {"titulo": "Dije Arbol Vida Redondo Con Baño De Plata", "color": None},
    {"titulo": "Dije Ala Mediana Piedra", "color": None},
    {"titulo": "Dije Ambar Del Báltico Con Pino", "color": "Ambar"},
    {"titulo": "Dije Pendulo Piramide", "color": None},
    {"titulo": "Dije Canasta 7 Chacras Baño De Plata", "color": None},
    {"titulo": "Dije Drusa Amatista De Calidad", "color": "Amatista"},
    {"titulo": "Dije Péndulo Arbol", "color": None},
    {"titulo": "Dije Atlantisita Xl", "color": "Atlantisita"},
    {"titulo": "Dije Corazon Grande Con Alambre", "color": None},
    {"titulo": "Dije Péndulo Y Palito 7 Chacras", "color": None},
    {"titulo": "Dije Drusa Amatista Con Aplique Y Baño De Plata", "color": "Amatista"},
    {"titulo": "Dije 7 Chacras Base Selenita Todo Baño", "color": "Selenita"}
]
for elemento in dijes:
    if elemento["color"]==None:
        print(elemento["titulo"])
    else:
        for indice in elemento["color"]:
            print(elemento["titulo"], elemento["color"][indice])

