DROP DATABASE IF EXISTS insumos;
CREATE DATABASE insumos;
USE insumos;
CREATE TABLE tipo_piedra (
    id_tipo_piedra INT NOT NULL AUTO_INCREMENT,
    tipo_piedra TEXT NOT NULL,
    PRIMARY KEY(id_tipo_piedra)
);

CREATE TABLE piedra (
    id_piedra INT NOT NULL AUTO_INCREMENT,
    piedra TEXT NOT NULL, -- El nombre específico de la piedra (ej: "Collar de Cuarzo")
    -- id_tipo_piedra_fk será la clave foránea que referencia a tipo_piedra
    id_tipo_piedra_fk INT NOT NULL,
    cantidad INTEGER,
    PRIMARY KEY(id_piedra),
    -- Define la clave foránea
    -- ON DELETE CASCADE: Si un tipo de piedra se elimina, todas las piedras de ese tipo también se eliminan.
    -- ON UPDATE CASCADE: Si el id_tipo_piedra cambia en la tabla tipo_piedra, se actualiza automáticamente aquí.
    FOREIGN KEY (id_tipo_piedra_fk) REFERENCES tipo_piedra(id_tipo_piedra) ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO `insumos`.`tipo_piedra` (`tipo_piedra`) VALUES
('Tiras 6 MM'),
('Tiras 4MM'),
('Escalla'),
('Tiras 8 MM'),
('Escallon');
INSERT INTO `insumos`.`piedra` (`piedra`, `id_tipo_piedra_fk`) VALUES
('7 Chacras', 1),
('7 Chacras', 2),
('7 Chacras', 3),
('7 Chacras', 4),
('7 Chacras', 5),
('Adularia', 1),
('Adularia', 2),
('Adularia', 3),
('Adularia', 4),
('Adularia', 5),
('Ágata', 1),
('Ágata', 2),
('Ágata', 3),
('Ágata', 4),
('Ágata', 5),
('Ágata Amarilla', 1),
('Ágata Amarilla', 2),
('Ágata Amarilla', 3),
('Ágata Amarilla', 4),
('Ágata Amarilla', 5),
('Ágata Azul', 1),
('Ágata Azul', 2),
('Ágata Azul', 3),
('Ágata Azul', 4),
('Ágata Azul', 5),
('Ágata Cinta Azul', 1),
('Ágata Cinta Azul', 2),
('Ágata Cinta Azul', 3),
('Ágata Cinta Azul', 4),
('Ágata Cinta Azul', 5),
('Ágata Cornalina', 1),
('Ágata Cornalina', 2),
('Ágata Cornalina', 3),
('Ágata Cornalina', 4),
('Ágata Cornalina', 5),
('Ágata Fucsia', 1),
('Ágata Fucsia', 2),
('Ágata Fucsia', 3),
('Ágata Fucsia', 4),
('Ágata Fucsia', 5),
('Ágata Musgosa', 1),
('Ágata Musgosa', 2),
('Ágata Musgosa', 3),
('Ágata Musgosa', 4),
('Ágata Musgosa', 5),
('Ágata Roja', 1),
('Ágata Roja', 2),
('Ágata Roja', 3),
('Ágata Roja', 4),
('Ágata Roja', 5),
('Ágata Verde', 1),
('Ágata Verde', 2),
('Ágata Verde', 3),
('Ágata Verde', 4),
('Ágata Verde', 5),
('Aguamarina', 1),
('Aguamarina', 2),
('Aguamarina', 3),
('Aguamarina', 4),
('Aguamarina', 5),
('Aguamarina Teñida', 1),
('Aguamarina Teñida', 2),
('Aguamarina Teñida', 3),
('Aguamarina Teñida', 4),
('Aguamarina Teñida', 5),
('Amatista', 1),
('Amatista', 2),
('Amatista', 3),
('Amatista', 4),
('Amatista', 5),
('Amazonita', 1),
('Amazonita', 2),
('Amazonita', 3),
('Amazonita', 4),
('Amazonita', 5),
('Cianita', 1),
('Cianita', 2),
('Cianita', 3),
('Cianita', 4),
('Cianita', 5),
('Cianita Negra', 1),
('Cianita Negra', 2),
('Cianita Negra', 3),
('Cianita Negra', 4),
('Cianita Negra', 5),
('Citrino', 1),
('Citrino', 2),
('Citrino', 3),
('Citrino', 4),
('Citrino', 5),
('Coral Rojo', 1),
('Coral Rojo', 2),
('Coral Rojo', 3),
('Coral Rojo', 4),
('Coral Rojo', 5),
('Cuarzo Ahumado', 1),
('Cuarzo Ahumado', 2),
('Cuarzo Ahumado', 3),
('Cuarzo Ahumado', 4),
('Cuarzo Ahumado', 5),
('Cuarzo Azul', 1),
('Cuarzo Azul', 2),
('Cuarzo Azul', 3),
('Cuarzo Azul', 4),
('Cuarzo Azul', 5),
('Cuarzo Cristal', 1),
('Cuarzo Cristal', 2),
('Cuarzo Cristal', 3),
('Cuarzo Cristal', 4),
('Cuarzo Cristal', 5),
('Cuarzo Rosa', 1),
('Cuarzo Rosa', 2),
('Cuarzo Rosa', 3),
('Cuarzo Rosa', 4),
('Cuarzo Rosa', 5),
('Cuarzo Verde', 1),
('Cuarzo Verde', 2),
('Cuarzo Verde', 3),
('Cuarzo Verde', 4),
('Cuarzo Verde', 5),
('Diamate Hérkimer', 1),
('Diamate Hérkimer', 2),
('Diamate Hérkimer', 3),
('Diamate Hérkimer', 4),
('Diamate Hérkimer', 5),
('Esmeralda', 1),
('Esmeralda', 2),
('Esmeralda', 3),
('Esmeralda', 4),
('Esmeralda', 5),
('Fluorita', 1),
('Fluorita', 2),
('Fluorita', 3),
('Fluorita', 4),
('Fluorita', 5),
('Fluorita Arcoiris', 1),
('Fluorita Arcoiris', 2),
('Fluorita Arcoiris', 3),
('Fluorita Arcoiris', 4),
('Fluorita Arcoiris', 5),
('Goldstone Azul', 1),
('Goldstone Azul', 2),
('Goldstone Azul', 3),
('Goldstone Azul', 4),
('Goldstone Azul', 5),
('Goldstone Marrón', 1),
('Goldstone Marrón', 2),
('Goldstone Marrón', 3),
('Goldstone Marrón', 4),
('Goldstone Marrón', 5),
('Granate', 1),
('Granate', 2),
('Granate', 3),
('Granate', 4),
('Granate', 5),
('Hematite', 1),
('Hematite', 2),
('Hematite', 3),
('Hematite', 4),
('Hematite', 5),
('Howlita Blanca', 1),
('Howlita Blanca', 2),
('Howlita Blanca', 3),
('Howlita Blanca', 4),
('Howlita Blanca', 5),
('Howlita Roja', 1),
('Howlita Roja', 2),
('Howlita Roja', 3),
('Howlita Roja', 4),
('Howlita Roja', 5),
('Howlita Turquesa', 1),
('Howlita Turquesa', 2),
('Howlita Turquesa', 3),
('Howlita Turquesa', 4),
('Howlita Turquesa', 5),
('Jade Chino', 1),
('Jade Chino', 2),
('Jade Chino', 3),
('Jade Chino', 4),
('Jade Chino', 5),
('Jade Taiwan', 1),
('Jade Taiwan', 2),
('Jade Taiwan', 3),
('Jade Taiwan', 4),
('Jade Taiwan', 5),
('Jaspe Dalmata', 1),
('Jaspe Dalmata', 2),
('Jaspe Dalmata', 3),
('Jaspe Dalmata', 4),
('Jaspe Dalmata', 5),
('Jaspe Madera', 1),
('Jaspe Madera', 2),
('Jaspe Madera', 3),
('Jaspe Madera', 4),
('Jaspe Madera', 5),
('Jaspe Mokaite', 1),
('Jaspe Mokaite', 2),
('Jaspe Mokaite', 3),
('Jaspe Mokaite', 4),
('Jaspe Mokaite', 5),
('Jaspe rojo', 1),
('Jaspe rojo', 2),
('Jaspe rojo', 3),
('Jaspe rojo', 4),
('Jaspe rojo', 5),
('Jaspe Verde', 1),
('Jaspe Verde', 2),
('Jaspe Verde', 3),
('Jaspe Verde', 4),
('Jaspe Verde', 5),
('Labradorita', 1),
('Labradorita', 2),
('Labradorita', 3),
('Labradorita', 4),
('Labradorita', 5),
('Labradorita Azul', 1),
('Labradorita Azul', 2),
('Labradorita Azul', 3),
('Labradorita Azul', 4),
('Labradorita Azul', 5),
('Labradorita Gris', 1),
('Labradorita Gris', 2),
('Labradorita Gris', 3),
('Labradorita Gris', 4),
('Labradorita Gris', 5),
('Labradorita Verde', 1),
('Labradorita Verde', 2),
('Labradorita Verde', 3),
('Labradorita Verde', 4),
('Labradorita Verde', 5),
('Lapislazuli', 1),
('Lapislazuli', 2),
('Lapislazuli', 3),
('Lapislazuli', 4),
('Lapislazuli', 5),
('Malaquita', 1),
('Malaquita', 2),
('Malaquita', 3),
('Malaquita', 4),
('Malaquita', 5),
('Malaquita Natural', 1),
('Malaquita Natural', 2),
('Malaquita Natural', 3),
('Malaquita Natural', 4),
('Malaquita Natural', 5),
('Moldavita', 1),
('Moldavita', 2),
('Moldavita', 3),
('Moldavita', 4),
('Moldavita', 5),
('Nacar', 1),
('Nacar', 2),
('Nacar', 3),
('Nacar', 4),
('Nacar', 5),
('Nacar Blanco', 1),
('Nacar Blanco', 2),
('Nacar Blanco', 3),
('Nacar Blanco', 4),
('Nacar Blanco', 5),
('Obsidiana Dorada', 1),
('Obsidiana Dorada', 2),
('Obsidiana Dorada', 3),
('Obsidiana Dorada', 4),
('Obsidiana Dorada', 5),
('Obsidiana Negra', 1),
('Obsidiana Negra', 2),
('Obsidiana Negra', 3),
('Obsidiana Negra', 4),
('Obsidiana Negra', 5),
('Obsidiana Nevada', 1),
('Obsidiana Nevada', 2),
('Obsidiana Nevada', 3),
('Obsidiana Nevada', 4),
('Obsidiana Nevada', 5),
('Obsidiana Plateada', 1),
('Obsidiana Plateada', 2),
('Obsidiana Plateada', 3),
('Obsidiana Plateada', 4),
('Obsidiana Plateada', 5),
('Ojo de Buey', 1),
('Ojo de Buey', 2),
('Ojo de Buey', 3),
('Ojo de Buey', 4),
('Ojo de Buey', 5),
('Ojo de Gato', 1),
('Ojo de Gato', 2),
('Ojo de Gato', 3),
('Ojo de Gato', 4),
('Ojo de Gato', 5),
('Ojo De Halcon', 1),
('Ojo De Halcon', 2),
('Ojo De Halcon', 3),
('Ojo De Halcon', 4),
('Ojo De Halcon', 5),
('Ojo de Tigre', 1),
('Ojo de Tigre', 2),
('Ojo de Tigre', 3),
('Ojo de Tigre', 4),
('Ojo de Tigre', 5),
('Onix Blaco Brilloso', 1),
('Onix Blaco Brilloso', 2),
('Onix Blaco Brilloso', 3),
('Onix Blaco Brilloso', 4),
('Onix Blaco Brilloso', 5),
('Onix Blanco Opaco', 1),
('Onix Blanco Opaco', 2),
('Onix Blanco Opaco', 3),
('Onix Blanco Opaco', 4),
('Onix Blanco Opaco', 5),
('Onix Champagne', 1),
('Onix Champagne', 2),
('Onix Champagne', 3),
('Onix Champagne', 4),
('Onix Champagne', 5),
('Onix Cielo', 1),
('Onix Cielo', 2),
('Onix Cielo', 3),
('Onix Cielo', 4),
('Onix Cielo', 5),
('Onix Jaspeado', 1),
('Onix Jaspeado', 2),
('Onix Jaspeado', 3),
('Onix Jaspeado', 4),
('Onix Jaspeado', 5),
('Onix Marrón', 1),
('Onix Marrón', 2),
('Onix Marrón', 3),
('Onix Marrón', 4),
('Onix Marrón', 5),
('Onix Negro', 1),
('Onix Negro', 2),
('Onix Negro', 3),
('Onix Negro', 4),
('Onix Negro', 5),
('Onix Negro Opaco', 1),
('Onix Negro Opaco', 2),
('Onix Negro Opaco', 3),
('Onix Negro Opaco', 4),
('Onix Negro Opaco', 5),
('Onix Verde Limón', 1),
('Onix Verde Limón', 2),
('Onix Verde Limón', 3),
('Onix Verde Limón', 4),
('Onix Verde Limón', 5),
('Opalina', 1),
('Opalina', 2),
('Opalina', 3),
('Opalina', 4),
('Opalina', 5),
('Peridoto', 1),
('Peridoto', 2),
('Peridoto', 3),
('Peridoto', 4),
('Peridoto', 5),
('Piedra Luna Natural', 1),
('Piedra Luna Natural', 2),
('Piedra Luna Natural', 3),
('Piedra Luna Natural', 4),
('Piedra Luna Natural', 5),
('Piedra Luna Natural (Adularia)', 1),
('Piedra Luna Natural (Adularia)', 2),
('Piedra Luna Natural (Adularia)', 3),
('Piedra Luna Natural (Adularia)', 4),
('Piedra Luna Natural (Adularia)', 5),
('Piedra Sol', 1),
('Piedra Sol', 2),
('Piedra Sol', 3),
('Piedra Sol', 4),
('Piedra Sol', 5),
('Pirita', 1),
('Pirita', 2),
('Pirita', 3),
('Pirita', 4),
('Pirita', 5),
('Prehnita', 1),
('Prehnita', 2),
('Prehnita', 3),
('Prehnita', 4),
('Prehnita', 5),
('Rodocrocita', 1),
('Rodocrocita', 2),
('Rodocrocita', 3),
('Rodocrocita', 4),
('Rodocrocita', 5),
('Rodocrosita', 1),
('Rodocrosita', 2),
('Rodocrosita', 3),
('Rodocrosita', 4),
('Rodocrosita', 5),
('Rodonita', 1),
('Rodonita', 2),
('Rodonita', 3),
('Rodonita', 4),
('Rodonita', 5),
('Rubí', 1),
('Rubí', 2),
('Rubí', 3),
('Rubí', 4),
('Rubí', 5),
('Selenita', 1),
('Selenita', 2),
('Selenita', 3),
('Selenita', 4),
('Selenita', 5),
('Serpentina', 1),
('Serpentina', 2),
('Serpentina', 3),
('Serpentina', 4),
('Serpentina', 5),
('Shungita', 1),
('Shungita', 2),
('Shungita', 3),
('Shungita', 4),
('Shungita', 5),
('Sodalita', 1),
('Sodalita', 2),
('Sodalita', 3),
('Sodalita', 4),
('Sodalita', 5),
('Topacio', 1),
('Topacio', 2),
('Topacio', 3),
('Topacio', 4),
('Topacio', 5),
('Topacio Azul', 1),
('Topacio Azul', 2),
('Topacio Azul', 3),
('Topacio Azul', 4),
('Topacio Azul', 5),
('Turmalina', 1),
('Turmalina', 2),
('Turmalina', 3),
('Turmalina', 4),
('Turmalina', 5),
('Turmalina Azul', 1),
('Turmalina Azul', 2),
('Turmalina Azul', 3),
('Turmalina Azul', 4),
('Turmalina Azul', 5),
('Turmalina Negra', 1),
('Turmalina Negra', 2),
('Turmalina Negra', 3),
('Turmalina Negra', 4),
('Turmalina Negra', 5),
('Turmalina Roja', 1),
('Turmalina Roja', 2),
('Turmalina Roja', 3),
('Turmalina Roja', 4),
('Turmalina Roja', 5),
('Turmalina Verde', 1),
('Turmalina Verde', 2),
('Turmalina Verde', 3),
('Turmalina Verde', 4),
('Turmalina Verde', 5),
('Turquesa Imperial', 1),
('Turquesa Imperial', 2),
('Turquesa Imperial', 3),
('Turquesa Imperial', 4),
('Turquesa Imperial', 5),
('Turquesa Natural', 1),
('Turquesa Natural', 2),
('Turquesa Natural', 3),
('Turquesa Natural', 4),
('Turquesa Natural', 5),
('Unakita', 1),
('Unakita', 2),
('Unakita', 3),
('Unakita', 4),
('Unakita', 5),
('Zircón', 1),
('Zircón', 2),
('Zircón', 3),
('Zircón', 4),
('Zircón', 5),
('Jaspe Cebra', 1),
('Jaspe Cebra', 2),
('Jaspe Cebra', 3),
('Jaspe Cebra', 4),
('Jaspe Cebra', 5),
('Turquenita', 1),
('Turquenita', 2),
('Turquenita', 3),
('Turquenita', 4),
('Turquenita', 5),
('Azurita', 1),
('Azurita', 2),
('Azurita', 3),
('Azurita', 4),
('Azurita', 5);